[package]
name = "config-parsing-2"
version = "0.1.0"
authors = ["Steven Engler <opara@cs.georgetown.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
